// Generated by CoffeeScript 1.6.3
(function() {
  var appController, fs, _;

  fs = require('fs');

  _ = require('lodash');

  appController = {
    layout: 'default',
    beforeRender: function() {},
    render: function(name, layout) {
      return this.beforeRender();
    }
  };

  /*
    Modules are automatically loaded once they are declared in the controllers directory.
  */


  fs.readdirSync(__dirname).forEach(function(file) {
    var controller, moduleName;
    if (file !== 'index.js') {
      moduleName = file.substr(0, file.indexOf('.'));
      controller = require('./' + moduleName);
      if (!_.isFunction(controller) && !_.isArray(controller) && _.isObject(controller)) {
        return exports[moduleName] = _.assign(appController, controller);
      } else {
        return exports[moduleName] = controller;
      }
    }
  });

  /*
    Use with ExpressJS framework
  ## #
  module.exports = (app) ->
    # homepage
    app.get '/', (req, res, next) ->
      res.render 'index.handlebars', data:{}
  
  
    # All Controllers
    require('./users') app
  */


}).call(this);
